### ISSUE TITLE
Parse null exception for Menucast/1.52 CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)

### ISSUE THREAD

**Issue by longzheng** [ua-parser/uap-csharp#23]
Using the latest uap-core https://github.com/ua-parser/uap-core/commit/eb8cf22971048e88d6f22f00dbf6de5a3bc5a788

Trying to parse ``Menucast/1.52 CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)`` causes a null reference exception

Code

```csharp
var parser = Parser.FromYaml(...);
var result = parser.Parse("Menucast/1.52 CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)");
```

Exception

```csharp
System.NullReferenceException : Object reference not set to an instance of an object.
   at UAParser.Parser.Parsers.<Device>b__23(<>f__AnonymousType3`2 <>h__TransparentIdentifier1e, String model)
   at UAParser.RegexBinderBuilder.<>c__DisplayClass1`3.<SelectMany>b__0(Match m, IEnumerator`1 num)
   at UAParser.Parser.Parsers.<>c__DisplayClass48`1.<Create>b__46(String input)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at UAParser.Parser.<>c__DisplayClass7`2.<CreateParser>b__4(String ua)
   at UAParser.Parser.Parse(String uaString)
```

**Comment by longzheng** [comment]
This seems to be similar to this issue https://github.com/ua-parser/uap-core/issues/238

**Comment by Plasma** [comment]
A few other user-agent parsing failures:

```
com.apple.WebKit.Networking/12603.1.30.0.34 CFNetwork/811.4.18 Darwin/16.5.0 (x86_64)

CFNetwork/720.5.7 Darwin/14.5.0 (x86_64)
```

**Comment by Plasma** [comment]
I have found that if we update uap-core to the latest revision, a few of existing tests fail with the NullRef exception already.

Using "git bisect" I was able to narrow down this commit as being the one causing the test failures on uap-csharp when uap-core is updated to the more recent revision: https://github.com/ua-parser/uap-core/commit/4fb556e84804144b29f49f52f550d3f6d14cd9d0

**Comment by enemaerke** [comment]
Just update to the latest regex.yaml strings and all tests passes, so I'm closing this issue
